module.exports = {
    container: {
        backgroundColor: '#000000',
        flexDirection: 'column',
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 25,
        elevation: 3,
    },
    container_klein: {
        flexDirection: 'row',
    },
    foto: {
        width: 26,
        height: 25,
    },
    title: {
        paddingVertical: 5,
        paddingRight: 55,
        paddingHorizontal: 0,
        fontSize: 25,
        lineHeight: 21,
        fontWeight: "300",
        letterSpacing: 0.25,
        color: 'white',
    },
    time:{
        paddingVertical: 3,
        paddingHorizontal: 5,
        paddingRight: 55,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: "300",
        letterSpacing: 0.25,
        color: 'white',
    },
    date:{
        paddingVertical: 3,
        paddingHorizontal: 5,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: "300",
        letterSpacing: 0.25,
        color: 'white',
    },
}
