export default {
    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        backgroundColor: "#0000004D",
    },
    innerContainer: {
        alignItems: "center",
        justifyContent: "space-evenly",
        width: "80%",
        height: "70%",
        minHeight: 500,
        backgroundColor: "black",
        borderRadius: 20,
        paddingLeft: "5%",
        paddingRight: "5%",
    },
    text: {
        fontFamily: "Sen_400Regular",
        color: "white",
        fontSize: 24,
    },
    textInput: {
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 30,
        borderWidth: 1,
        textAlignVertical: "top",
        fontSize: 16,
        lineHeight: 21,
        letterSpacing: 0.25,
        color: "black",
        backgroundColor: "white",
        fontFamily: "Sen_400Regular",
        height: "60%",
        width: "100%",
    },
    buttonContainer: {
        flexDirection: "row",
        justifyContent: "space-around",
        width: "100%",
    },
    button: {
        paddingVertical: 10,
        paddingHorizontal: 20,
    },
    buttonFont: {
        fontSize: 22,
    },
}