export default {
    container: {
        width: "100%",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 10,
    },
    text: {
        fontFamily: "Sen_400Regular",
        fontSize: 20,
        color: "black",
        width: "90%",
    },
    personContainer: {
        backgroundColor: "white",
        width: "83%",
        height: 55,
        paddingHorizontal: 17,
        borderRadius: 30,
        borderWidth: 2,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    userIcon: {
        position: "absolute",
        right: 15,
    },
    notificationContainer: {
        backgroundColor: "black",
        height: 45,
        width: 45,
        borderRadius: 60,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 6,
    },
    image: {
        alignItems: 'center',
        width:  30,
        height: 30,
        alignSelf: "center",
        justifyContent: 'flex-end',
        position: "absolute",
        right: 15,
    },
}
