module.exports = {

    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        height: "100%",
        backgroundColor: "#0000004D",
    },
    innerContainer: {
        alignItems: "center",
        justifyContent: "space-evenly",
        width: "85%",
        height: "50%",
        minHeight: 200,
        backgroundColor: "black",
        borderRadius: 20,
        paddingLeft: "5%",
        paddingRight: "5%",
    },
    textInput: {
        flex: 0.1,
        paddingVertical: 13,
        paddingHorizontal: 28,
        borderRadius: 30,
        borderWidth: 1,
        textAlignVertical: "top",
        fontSize: 16,
        lineHeight: 21,
        letterSpacing: 0.25,
        color: "black",
        backgroundColor: "white",
        fontFamily: "Sen_400Regular",
        minWidth: 125,
        maxWidth: 125,
        minHeight: 50,
        maxHeight: 50,
    },
    buttonContainer:{
        flexDirection: 'row',
        justifyContent: "space-around",
        width: "100%",
    },
    text: {
        fontFamily: "Sen_400Regular",
        color: "white",
        fontSize: 20,
    },
    button: {
        height: 60,
        width: 60,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 50,
        backgroundColor: "white",
    },
}
