module.exports = {

    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        height: "100%",
        backgroundColor: "#0000004D",
    },
    innerContainer: {
        alignItems: "center",
        justifyContent: "space-evenly",
        width: "85%",
        height: "45%",
        minHeight: 250,
        backgroundColor: "black",
        borderRadius: 20,
        paddingLeft: "5%",
        paddingRight: "5%",
    },
    textInput: {
        flex: 0.1,
        paddingVertical: 13,
        paddingHorizontal: 28,
        borderRadius: 30,
        textAlignVertical: "center",
        textAlign: "center",
        fontSize: 22,
        letterSpacing: 0.25,
        color: "black",
        backgroundColor: "white",
        fontFamily: "Sen_400Regular",
        minWidth: 160,
        width: "70%",
        minHeight: 40,
        maxHeight: 60,
    },
    buttonContainer:{
        flexDirection: 'row',
        justifyContent: "space-between",
        width: "70%",
    },
    text: {
        fontFamily: "Sen_400Regular",
        color: "white",
        fontSize: 24,
        textAlign: "center",
    },
    button: {
        height: 60,
        width: 60,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 50,
        backgroundColor: "white",
    },
}
