import notes from "./allNotes/allNotesScreen";
import confirm from "./confirm/confirmScreen";
import main from "./main/mainScreen";
import scan from "./scan/scanScreen";
import selectPerson from "./selectPerson/selectPersonScreen";
import selectTool from "./selectTool/selectToolScreen";
import share from "./share/shareScreen";
import start from "./start/startScreen";
import join from "./join/joinScreen";
import createPoll from "./createPoll/createPollScreen";

export let Notes = notes;
export let Confirm = confirm;
export let Main = main;
export let Scan = scan;
export let SelectPerson = selectPerson;
export let SelectTool = selectTool;
export let Share = share;
export let Start = start;
export let Join = join;
export let CreatePoll = createPoll;