
module.exports = {
    container: {
        flexDirection: 'row',
        height: 60,
        width: "95%",
        minWidth: 180,
        alignItems: 'center',
        justifyContent: "center",
        marginTop: 10,
    },
    text: {
        backgroundColor: "white",
        borderColor: "black",
        borderWidth: 2,
        borderRadius: 35,
        paddingVertical: 10,
        paddingHorizontal: 28,
        fontSize: 24,
        letterSpacing: 0.25,
        color: "black",
        fontFamily: "Sen_400Regular",
        textAlignVertical: "center",
    },
    iconContainer: {
        backgroundColor: "black",
        borderRadius: 30,
        height: 45,
        width: 45,
        alignItems: "center",
        justifyContent: "center",
        position: "absolute",
        right: 5,
    },
}
